# Generated by Django 5.1.5 on 2025-01-28 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sessao',
            options={'verbose_name': 'Sessão', 'verbose_name_plural': 'Sessões'},
        ),
    ]
