# Generated by Django 5.1.5 on 2025-01-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cidade_snack'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Snack',
            new_name='Snacks',
        ),
    ]
