# Generated by Django 5.1.5 on 2025-02-01 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_snack_delete_snacks_alter_cidade_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snaks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snaks', to='app.funcionario')),
            ],
            options={
                'verbose_name': 'Snak',
                'verbose_name_plural': 'Snaks',
            },
        ),
        migrations.DeleteModel(
            name='Snack',
        ),
    ]
