# Generated by Django 5.1.5 on 2025-02-01 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cidade_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.CharField(default='--', max_length=100, unique=True),
        ),
    ]
